FROM node:20-alpine

# Use built-in node user
WORKDIR /workspace
RUN chown -R node:node /workspace

USER node

# Keep container alive and run the command given by worker
ENTRYPOINT ["node", "main.js"]
